-- ===========================================================================
-- LernRaum Protokoll — Leistungen (SA/Test/Prüfung) + gemeinsamer Kalender
-- ===========================================================================
-- Im Supabase SQL Editor ausführen. Abschnittsweise möglich.
-- Legt eine neue Tabelle an und erweitert die Leserechte auf Einheiten,
-- damit Lehrer den gemeinsamen Kalender sehen. Es werden keine Daten
-- gelöscht.
--
-- Ergänzt db/security_policies.sql.
-- ===========================================================================


-- --- Abschnitt 1: Tabelle für Leistungen ---------------------------------
-- Eine Zeile = eine Schularbeit / ein Test / eine Prüfung eines Schülers.
-- Die Bewertung kann als Schulnote (1-5) und/oder als Symbol (+ ~ -)
-- festgehalten werden; mindestens eines von beiden muss gesetzt sein.
--
-- Achtung auf die zwei Skalen im Projekt:
--   protocol_attendance.progress  5 = sehr gut  ... 1 = schlecht
--   student_assessments.grade_number  1 = Sehr gut ... 5 = Nicht genügend
-- Letzteres ist die übliche Schulnote und wird hier bewusst so geführt.
create table if not exists public.student_assessments (
  id            bigint generated by default as identity primary key,
  -- Bewusst "set null": wird ein Protokoll gelöscht, darf die Note einer
  -- Schularbeit nicht mitverschwinden — vor allem nicht bei einem erst
  -- angekündigten Termin.
  protocol_id   bigint      references public.protocols(id) on delete set null,
  session_id    bigint      references public.sessions(id)  on delete set null,
  student_id    bigint      not null references public.students(id) on delete cascade,
  student_name  text        not null,
  teacher_id    uuid        references public.profiles(id) on delete set null,
  teacher_name  text,
  subject       text,
  exam_type     text        not null,
  exam_date     date        not null,
  grade_number  smallint,
  grade_symbol  text,
  notes         text,
  created_at    timestamptz not null default now(),

  constraint student_assessments_exam_type_check
    check (exam_type in ('Schularbeit', 'Test', 'Prüfung')),
  constraint student_assessments_grade_number_check
    check (grade_number is null or grade_number between 1 and 5),
  constraint student_assessments_grade_symbol_check
    check (grade_symbol is null or grade_symbol in ('+', '~', '-')),
  -- Eine Leistung ohne jede Bewertung wäre ein leerer Eintrag.
  constraint student_assessments_grade_present_check
    check (grade_number is not null or grade_symbol is not null)
);

create index if not exists student_assessments_student_idx
  on public.student_assessments (student_id, exam_date desc);
create index if not exists student_assessments_protocol_idx
  on public.student_assessments (protocol_id);


-- --- Abschnitt 2: Rechte auf Leistungen ----------------------------------
alter table public.student_assessments enable row level security;

-- Lesen: alle angemeldeten Lehrer. Ein Schüler wechselt im Lauf des Jahres
-- die Lehrkraft; die Notenentwicklung muss darum für das Team sichtbar sein.
drop policy if exists "assessments_select" on public.student_assessments;
create policy "assessments_select" on public.student_assessments
  for select to authenticated using (true);

-- Schreiben: der eintragende Lehrer für seine eigenen Einträge.
drop policy if exists "assessments_write_own" on public.student_assessments;
create policy "assessments_write_own" on public.student_assessments
  for all to authenticated
  using (auth.uid() = teacher_id)
  with check (auth.uid() = teacher_id);

-- Schreiben: Admins dürfen korrigieren und löschen.
drop policy if exists "assessments_write_admin" on public.student_assessments;
create policy "assessments_write_admin" on public.student_assessments
  for all to authenticated
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin));


-- --- Abschnitt 3: Gemeinsamer Kalender -----------------------------------
-- Bisher sah ein Lehrer nur die eigenen Einheiten. Für die Wochenansicht
-- über alle Lehrer braucht er Leserecht auf alle Einheiten.
-- Geschrieben wird weiterhin nur vom Admin (bzw. am eigenen Eintrag) —
-- der Kalender selbst ist reine Anzeige.
alter table public.sessions enable row level security;

drop policy if exists "sessions_select_authenticated" on public.sessions;
create policy "sessions_select_authenticated" on public.sessions
  for select to authenticated using (true);

-- Admins planen und verschieben.
drop policy if exists "sessions_admin_write" on public.sessions;
create policy "sessions_admin_write" on public.sessions
  for all to authenticated
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin));

-- Die eigene Einheit darf der Lehrer ändern, und eine zur Vertretung
-- freigegebene Einheit darf übernommen werden (accept_substitution).
drop policy if exists "sessions_update_own" on public.sessions;
create policy "sessions_update_own" on public.sessions
  for update to authenticated
  using (
    auth.uid() = teacher_id
    or exists (
      select 1 from public.substitution_requests r
      where r.session_id = public.sessions.id
    )
  )
  with check (true);

-- Die Schülerzuordnung wird für die Anzeige (Anzahl, Fach) mitgelesen.
alter table public.session_students enable row level security;

drop policy if exists "session_students_select_authenticated" on public.session_students;
create policy "session_students_select_authenticated" on public.session_students
  for select to authenticated using (true);

drop policy if exists "session_students_admin_write" on public.session_students;
create policy "session_students_admin_write" on public.session_students
  for all to authenticated
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin));


-- --- Abschnitt 4: Kontrolle ----------------------------------------------
-- Nach dem Ausführen prüfen, dass die Policies sitzen:
--
--   select tablename, policyname, cmd
--   from pg_policies
--   where tablename in ('student_assessments', 'sessions', 'session_students')
--   order by tablename, policyname;
